language: node_js
dist: trusty
node_js:
  - "8"
sudo: false
notifications:
  email: false
before_install:
  - gem install sass
  - gem install compass
  - npm install -g yarn --cache-min 999999999
  - npm install -g bower grunt-cli
install:
  - yarn
script:
  - npm run package
